#!/usr/bin/env python3
"""Generate fpops.8kn: operation stubs for the FPVEC floating-point test.

Each stub loads its operands from ga/gb, clears the EPU sticky flags,
executes the operation with an explicit rounding-precision field
(1 = single, 2 = double), stores the result in gz and saves the sticky
flags in gfl.  The flags are read after the store because the FPE
checks overflow and underflow against the extended range and only
narrows to the destination format's range when the result is stored.  The assembler only encodes extended-precision register
operations, so the instruction words are emitted raw.
"""
OPS = [("add", 0x4280), ("sub", 0x4290), ("mul", 0x42B0),
       ("div", 0x42A0), ("sqrt", 0x82C0)]

out = ["; Generated by tests/fpe/genops.py -- do not edit.",
       "\t.GLOBAL _ga,_gb,_gz,_gfl,_gcc,_gmode,_setmode",
       "\t.GLOBAL _s_cmp,_d_cmp,_i_s,_i_d,_s_i,_d_i,_s_d,_d_s,_s_rti,_d_rti"]
for p in "sd":
    for n, _ in OPS:
        out.append("\t.GLOBAL _%s_%s" % (p, n))
out += ["", "__text\t.sect", "",
        "_setmode:", "\tld\tr0,_gmode", "\tldk\tr1,#0",
        "\tfldctl\tuser,r0", "\tret", ""]
for p, fmt, mem in (("s", 1, "flds"), ("d", 2, "fldd")):
    for n, base in OPS:
        out += ["_%s_%s:" % (p, n),
                "\t%s\tf0,_ga" % mem,
                "\t%s\tf2,_%s" % (mem, "ga" if n == "sqrt" else "gb"),
                "\tldk\tr0,#0", "\tldk\tr1,#0",
                "\tfldctl\tfflags,rr0",
                "\t.word\t08e04h,0%04xh" % (base | fmt << 12),
                "\t%s\t_gz,f0" % mem,
                "\tfldctl\trr0,fflags",
                "\tld\t_gfl,r1",
                "\tret", ""]
CLEAR = ["\tldk\tr0,#0", "\tldk\tr1,#0", "\tfldctl\tfflags,rr0"]
READ = ["\tfldctl\trr0,fflags", "\tld\t_gcc,r0", "\tld\t_gfl,r1", "\tret", ""]
extra = []
# compare: raw comparison flags (byte 89) go to gcc
for p, mem in (("s", "flds"), ("d", "fldd")):
    extra += ["_%s_cmp:" % p, "\t%s\tf0,_ga" % mem, "\t%s\tf2,_gb" % mem]
    extra += CLEAR + ["\t.word\t08e04h,04210h"] + READ
# integer -> float
for p, mem in (("s", "flds"), ("d", "fldd")):
    extra += ["_i_%s:" % p, "\tldl\trr6,_ga"] + CLEAR + ["\tfldil\tf0,rr6"]
    extra += ["\t%s\t_gz,f0" % mem]
    extra += READ
# float -> integer (flags cleared after the operand load)
for p, mem in (("s", "flds"), ("d", "fldd")):
    extra += ["_%s_i:" % p, "\t%s\tf0,_ga" % mem] + CLEAR
    extra += ["\tfldil\trr6,f0", "\tldl\t_gz,rr6"] + READ
# float <-> float
for n, a, b in (("s_d", "flds", "fldd"), ("d_s", "fldd", "flds")):
    extra += ["_%s:" % n, "\t%s\tf0,_ga" % a] + CLEAR
    extra += ["\t%s\t_gz,f0" % b] + READ
# round to integer
for p, mem, fmt in (("s", "flds", 1), ("d", "fldd", 2)):
    extra += ["_%s_rti:" % p, "\t%s\tf2,_ga" % mem] + CLEAR
    extra += ["\t.word\t08e04h,0%04xh" % (0x82D0 | fmt << 12),
              "\t%s\t_gz,f0" % mem] + READ
open("fpops.8kn", "w").write("\n".join(out + extra) + "\n")
